# Copyright Open Charts Community. All Rights Reserved.
# SPDX-License-Identifier: MIT

annotations:
  category: Infrastructure
  licenses: MIT
apiVersion: v2
# Please make sure that version and appVersion are always the same.
appVersion: 2.31.3
description: A Library Helm Chart for grouping common logic between open charts. This chart is not deployable by itself.
home: https://github.com/open-charts/charts
icon: https://raw.githubusercontent.com/open-charts/charts/main/logo.png
keywords:
  - common
  - helper
  - template
  - function
  - open-charts
maintainers:
  - name: Open Charts Community
    url: https://github.com/open-charts/charts
name: common
sources:
  - https://github.com/open-charts/charts/tree/main/charts/common
type: library
version: 2.31.3
